import { RatingItem } from '@/shared/api/dailyAssignmentApt';

export const fakeRating: RatingItem[] = [
  {
    userModel: {
      id: 1,
      email: 'user1@example.com',
      firstName: 'Максим',
      secondName: 'Яременко',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 120,
    place: 1,
  },
  {
    userModel: {
      id: 2,
      email: 'user2@example.com',
      firstName: 'Олена',
      secondName: 'Ковальчук',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 115,
    place: 2,
  },
  {
    userModel: {
      id: 8,
      email: 'user3@example.com',
      firstName: 'Ігор',
      secondName: 'Сидоренко',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 112,
    place: 12,
  },
  {
    userModel: {
      id: 4,
      email: 'user4@example.com',
      firstName: 'Анна',
      secondName: 'Кравченко',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 110,
    place: 4,
  },
  {
    userModel: {
      id: 5,
      email: 'user5@example.com',
      firstName: 'Юрій',
      secondName: 'Ткаченко',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 108,
    place: 5,
  },
  {
    userModel: {
      id: 6,
      email: 'user6@example.com',
      firstName: 'Катерина',
      secondName: 'Литвиненко',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 105,
    place: 6,
  },
  {
    userModel: {
      id: 7,
      email: 'user7@example.com',
      firstName: 'Владислав',
      secondName: 'Мельник',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 100,
    place: 7,
  },
  {
    userModel: {
      id: 3,
      email: 'user8@example.com',
      firstName: 'Тетяна',
      secondName: 'Козак',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 95,
    place: 8,
  },
  {
    userModel: {
      id: 9,
      email: 'user9@example.com',
      firstName: 'Богдан',
      secondName: 'Нікітін',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 90,
    place: 9,
  },
  {
    userModel: {
      id: 10,
      email: 'user10@example.com',
      firstName: 'Інна',
      secondName: 'Демченко',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 88,
    place: 10,
  },
  {
    userModel: {
      id: 11,
      email: 'user11@example.com',
      firstName: 'Олександр',
      secondName: 'Петренко',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 85,
    place: 11,
  },
  {
    userModel: {
      id: 12,
      email: 'user12@example.com',
      firstName: 'Дарина',
      secondName: 'Шевченко',
      statisticModelId: null,
      educationClassesIds: [],
      roles: ['student'],
    },
    score: 80,
    place: 3,
  },
];
